project:
  type: website
  output-dir: docs

website:
  title: "CMEP coding blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cmep-ms
      - icon: link-45deg
        href: http://extension.msstate.edu/crec-coastal-marine-ext-program 

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

