project:
  type: website
  output-dir: docs

website:
  title: "CMEP coding blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cmep-ms

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

